// intrface.h
//
// Generated by C DriverWizard 3.2.0 (Build 2485)
// Requires DDK Only
// File created on 4/16/2008
//

// Define an Interface Guid for KadyUsbTest device class.
// This GUID is used to register (IoRegisterDeviceInterface)
// an instance of an interface so that user application
// can control the KadyUsbTest device.
//
//定义一个GUID，
//  {F4BDDAC5-EE5B-449C-9147-CC004247FB8A}
DEFINE_GUID(GUID_DEVINTERFACE_KADYUSB340,
    0xF4BDDAC5, 0xEE5B, 0x449C, 0x91, 0x47, 0xCC, 0x00, 0x42, 0x47, 0xFB, 0x8A);

// Define a Setup Class GUID for KadyUsbTest Class. This is same
// as the KADYUSBTEST CLASS guid in the INF files.
//
//  {96e73b6e-7a5a-11d4-9f24-0080c82727f4}
DEFINE_GUID(GUID_DEVCLASS_KADYUSBTEST,
    0x96e73b6e, 0x7a5a, 0x11d4, 0x9F, 0x24, 0x00, 0x80, 0xC8, 0x27, 0x27, 0xF4);

// GUID definition are required to be outside of header inclusion pragma to avoid
// error during precompiled headers.
//

#ifndef __INTRFACE_H__
#define __INTRFACE_H__

#define FILE_DEVICE_KADYUSB340  0x8000

// Define Interface reference/dereference routines for
// Interfaces exported by IRP_MN_QUERY_INTERFACE

#define KADYUSBTEST_IOCTL(index) \
    CTL_CODE(FILE_DEVICE_KADYUSB340, index, METHOD_BUFFERED, FILE_READ_DATA)


#endif // __INTRFACE_H__
