// KadyUsbTestDriver.h
//
// Generated by DriverWizard 3.2.0 (Build 2485)
// Requires DDK and DriverWorks
// File created on 4/16/2008
//
// This include file contains the definition of a subclass of KDriver.
// WDM drivers declare a subclass of KDriver and override member
// function DriverEntry and AddDevice.
//
#ifndef __KADYUSBTESTDRIVER_H__
#define __KADYUSBTESTDRIVER_H__

class KadyUsbTestDriver : public KDriver
{
	SAFE_DESTRUCTORS
public:
	// Member functions
	virtual NTSTATUS DriverEntry(PUNICODE_STRING RegistryPath);
	virtual NTSTATUS AddDevice(PDEVICE_OBJECT Pdo);
	virtual VOID Unload(VOID);

	void LoadRegistryParameters(PUNICODE_STRING RegistryPath);

protected:
	// Member data
	int		m_Unit;
};

#endif // __KADYUSBTESTDRIVER_H__
